# DATASET_DIR=./tf_train
# TRAIN_DIR=./log/
# CHECKPOINT_PATH=./checkpoints/vgg_16.ckpt
# python myTrain.py \
#     --train_dir=${TRAIN_DIR} \
#     --dataset_dir=${DATASET_DIR} \
#     --dataset_name=pascalvoc_2007 \
#     --dataset_split_name=train \
#     --model_name=ssd_300_vgg \
#     --checkpoint_path=${CHECKPOINT_PATH} \
#     --checkpoint_model_scope=vgg_16 \
#     --checkpoint_exclude_scopes=ssd_300_vgg/conv6,ssd_300_vgg/conv7,ssd_300_vgg/block8,ssd_300_vgg/block9,ssd_300_vgg/block10,ssd_300_vgg/block11,ssd_300_vgg/block4_box,ssd_300_vgg/block7_box,ssd_300_vgg/block8_box,ssd_300_vgg/block9_box,ssd_300_vgg/block10_box,ssd_300_vgg/block11_box \
#     --trainable_scopes=ssd_300_vgg/conv6,ssd_300_vgg/conv7,ssd_300_vgg/block8,ssd_300_vgg/block9,ssd_300_vgg/block10,ssd_300_vgg/block11,ssd_300_vgg/block4_box,ssd_300_vgg/block7_box,ssd_300_vgg/block8_box,ssd_300_vgg/block9_box,ssd_300_vgg/block10_box,ssd_300_vgg/block11_box \
#     --save_summaries_secs=60 \
#     --save_interval_secs=600 \
#     --weight_decay=0.0005 \
#     --optimizer=adam \
#     --learning_rate=0.1 \
#     --learning_rate_decay_factor=0.94 \
# #     --batch_size=16 
# --optimizer='momentum' \
tfrecord_path=/home/liupengli/myWork/FRE/FRE/tfrecord
checkpoint_path=/home/liupengli/myWork/FRE/checkpoints/vgg_16.ckpt
checkpoint_dir=/home/liupengli/myWork/FRE/checkpoints
summary_dir=/home/liupengli/myWork/FRE/summaries
python train.py \
    --tfrecord_path=${tfrecord_path} \
    --checkpoint_dir=${checkpoint_dir} \
    --checkpoint_path=${checkpoint_path} \
    --summary_dir=${summary_dir} \
    --save_steps=100 \
    --max_step=42000 
